"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import styles from "./high-impact.module.css";

type Dimension={id:string;label:string;score:number;maxScore:number;status:"strong"|"developing"|"critical";actions:string[]};
type Guideline={name:string;reason:string;officialUrl:string};
type JournalCheck={query:string;matchedName:string|null;publisher:string|null;issn:string[];homepage:string|null;openAlexEvidence:boolean;crossrefEvidence:boolean;doajSignal:boolean;isOpenAccess:boolean;apcUsd:number|null;feeStatus:string;hIndex:number|null;twoYearMeanCitedness:number|null;evidenceStatus:string;cautions:string[]};
type RelatedWork={id:string;title:string;year:number|null;citedByCount:number;journal:string|null;doi:string|null};
type Result={assessment:{score:number;verdict:string;dimensions:Dimension[];reportingGuidelines:Guideline[];deskRejectionRisks:string[];editorialHooks:string[];scamShieldRules:string[]};relatedWorks:RelatedWork[];journalChecks:JournalCheck[];aiReport:string|null;aiProvider:string|null;aiModel:string|null;generatedAt:string};
type LocalJob={id:string;clientName:string;title:string;field?:string;doi?:string;articleUrl?:string;[key:string]:unknown};

const blank={clientName:"",title:"",abstract:"",field:"",articleType:"Original research article",studyDesign:"",noveltyClaim:"",mainFinding:"",methodsSummary:"",manuscriptText:"",targetJournals:"",authorCountry:"Nigeria",fundingStatus:"No external funding / not specified"};

export default function HighImpactClient(){
  const [form,setForm]=useState(blank);const [jobs,setJobs]=useState<LocalJob[]>([]);const [jobId,setJobId]=useState("");const [result,setResult]=useState<Result|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{try{const raw=localStorage.getItem("publishai_admin_jobs");if(raw)setJobs(JSON.parse(raw));}catch{}},[]);
  const report=useMemo(()=>{if(!result)return"";return [`MABRIG PUBLISHAI — HIGH-IMPACT PUBLICATION ACCELERATOR`,`Client: ${form.clientName}`,`Manuscript: ${form.title}`,`Readiness: ${result.assessment.score}/100 — ${result.assessment.verdict}`,"",result.aiReport||"AI narrative was unavailable; use the structured readiness dimensions and live registry evidence below.","","DESK-REJECTION RISKS",...result.assessment.deskRejectionRisks.map((x,i)=>`${i+1}. ${x}`),"","ANTI-SCAM RULES",...result.assessment.scamShieldRules.map((x,i)=>`${i+1}. ${x}`)].join("\n");},[result,form.clientName,form.title]);
  function loadJob(id:string){setJobId(id);const j=jobs.find(x=>x.id===id);if(j)setForm({...blank,clientName:j.clientName||"",title:j.title||"",field:j.field||"",authorCountry:"Nigeria"});}
  function saveToJob(data:Result){try{const raw=localStorage.getItem("publishai_admin_jobs");if(!raw)return;const list=JSON.parse(raw) as LocalJob[];const index=list.findIndex(j=>j.id===jobId||(j.clientName===form.clientName&&j.title===form.title));if(index<0)return;const entry={generatedAt:data.generatedAt,score:data.assessment.score,verdict:data.assessment.verdict,deskRejectionRisks:data.assessment.deskRejectionRisks};const old=Array.isArray((list[index] as any).highImpactHistory)?(list[index] as any).highImpactHistory:[];(list[index] as any).latestHighImpactAssessment=entry;(list[index] as any).highImpactHistory=[entry,...old].slice(0,10);localStorage.setItem("publishai_admin_jobs",JSON.stringify(list));}catch{}}
  async function run(e:FormEvent){e.preventDefault();setLoading(true);setError("");setResult(null);try{const r=await fetch("/api/admin/high-impact-accelerator",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,targetJournals:form.targetJournals.split(/\n|;/).map(x=>x.trim()).filter(Boolean)})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Accelerator failed.");setResult(data);saveToJob(data);}catch(err){setError(err instanceof Error?err.message:"Accelerator failed.");}finally{setLoading(false)}}
  function download(){if(!report)return;const b=new Blob([report],{type:"text/plain;charset=utf-8"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=`${form.clientName||"client"}-high-impact-publication-plan.txt`.replace(/[^a-z0-9._-]+/gi,"-");a.click();URL.revokeObjectURL(u)}
  return <main className={styles.page}>
    <section className={styles.hero}><div><div className={styles.eyebrow}>HIGH-IMPACT PUBLICATION ACCELERATOR</div><h1>Turn a promising manuscript into a defensible top-journal submission strategy.</h1><p>Strengthen novelty, methods, reporting, title/abstract, journal targeting and editor pitch—while protecting lecturers from fake impact factors, predatory fees and unverifiable indexing claims.</p></div><div className={styles.heroBadge}>Publisher premium engine</div></section>
    <div className={styles.grid}>
      <form className={styles.card} onSubmit={run}>
        {jobs.length>0&&<label><span>Load existing client case</span><select value={jobId} onChange={e=>loadJob(e.target.value)}><option value="">New / manual case</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.clientName} — {j.title}</option>)}</select></label>}
        <div className={styles.sectionTitle}>1. Author & manuscript</div>
        <div className={styles.two}><label><span>Client / lecturer *</span><input required value={form.clientName} onChange={e=>setForm({...form,clientName:e.target.value})}/></label><label><span>Country</span><input value={form.authorCountry} onChange={e=>setForm({...form,authorCountry:e.target.value})}/></label></div>
        <label><span>Manuscript title *</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>
        <div className={styles.two}><label><span>Field</span><input value={form.field} onChange={e=>setForm({...form,field:e.target.value})} placeholder="e.g. Public Health"/></label><label><span>Article type</span><select value={form.articleType} onChange={e=>setForm({...form,articleType:e.target.value})}><option>Original research article</option><option>Systematic review</option><option>Review article</option><option>Case study</option><option>Short communication</option><option>Protocol</option></select></label></div>
        <label><span>Study design</span><input value={form.studyDesign} onChange={e=>setForm({...form,studyDesign:e.target.value})} placeholder="RCT, cross-sectional survey, cohort, qualitative, systematic review..."/></label>
        <label><span>Abstract *</span><textarea required value={form.abstract} onChange={e=>setForm({...form,abstract:e.target.value})} placeholder="Paste the complete abstract (80+ characters)."/></label>
        <div className={styles.sectionTitle}>2. High-impact positioning</div>
        <label><span>What is genuinely new?</span><textarea value={form.noveltyClaim} onChange={e=>setForm({...form,noveltyClaim:e.target.value})} placeholder="One precise gap + contribution. Avoid exaggerated 'first ever' claims unless verifiable."/></label>
        <label><span>Single most important finding</span><textarea value={form.mainFinding} onChange={e=>setForm({...form,mainFinding:e.target.value})}/></label>
        <label><span>Methods / statistics summary</span><textarea value={form.methodsSummary} onChange={e=>setForm({...form,methodsSummary:e.target.value})} placeholder="Sample/data source, design, variables, analysis, robustness, ethics..."/></label>
        <label><span>Manuscript / key sections</span><textarea className={styles.large} value={form.manuscriptText} onChange={e=>setForm({...form,manuscriptText:e.target.value})}/></label>
        <div className={styles.sectionTitle}>3. Journal & fee safety</div>
        <label><span>Journals being considered (one per line)</span><textarea value={form.targetJournals} onChange={e=>setForm({...form,targetJournals:e.target.value})} placeholder="Paste journals suggested by colleagues, agents or emails. PublishAI will check registry evidence."/></label>
        <label><span>Funding / APC situation</span><input value={form.fundingStatus} onChange={e=>setForm({...form,fundingStatus:e.target.value})} placeholder="No funding, grant-funded, needs waiver, institution can pay..."/></label>
        <button className={styles.primary} disabled={loading}>{loading?"Building high-impact strategy…":"Run High-Impact Publication Accelerator"}</button>{error&&<div className={styles.error}>{error}</div>}
      </form>
      <section className={styles.result}>{!result?<div className={styles.empty}><div><strong>High-impact strategy appears here</strong><p>Score the manuscript, identify top-journal blockers, verify proposed journal identities, map related scholarship and generate an editor-facing upgrade plan.</p></div></div>:<>
        <div className={styles.scoreHead}><div className={styles.score}>{result.assessment.score}</div><div><div className={styles.eyebrow}>SELECTIVE-JOURNAL READINESS</div><h2>{result.assessment.verdict}</h2><p>{result.aiProvider?`${result.aiProvider} / ${result.aiModel}`:"Structured evidence engine"} · {new Date(result.generatedAt).toLocaleString()}</p></div></div><div className={styles.progress}><span style={{width:`${result.assessment.score}%`}}/></div>
        <div className={styles.actions}><button onClick={()=>navigator.clipboard.writeText(report)}>Copy plan</button><button onClick={download}>Download</button><button onClick={()=>location.href="/admin/journal-matrix"}>Open Journal Matrix</button></div>
        <div className={styles.sectionTitle}>Readiness dimensions</div><div className={styles.dimensions}>{result.assessment.dimensions.map(d=><article key={d.id} className={`${styles.dimension} ${styles[d.status]}`}><strong>{d.label} — {d.score}/{d.maxScore}</strong><span>{d.status}</span><ul>{d.actions.map(a=><li key={a}>{a}</li>)}</ul></article>)}</div>
        <div className={styles.sectionTitle}>Reporting guideline route</div><div className={styles.chips}>{result.assessment.reportingGuidelines.map(g=><a className={styles.chip} href={g.officialUrl} target="_blank" rel="noreferrer" key={g.name}>{g.name}</a>)}</div>
        <div className={styles.sectionTitle}>Desk-rejection risks</div>{result.assessment.deskRejectionRisks.length?<ol>{result.assessment.deskRejectionRisks.map(x=><li key={x}>{x}</li>)}</ol>:<div className={styles.notice}>No major deterministic desk-rejection risks were flagged. Manual editorial review is still required.</div>}
        {result.journalChecks.length>0&&<><div className={styles.sectionTitle}>High-impact journal scam shield</div>{result.journalChecks.map(j=><article className={styles.journal} key={j.query}><strong>{j.query} → {j.matchedName||"No confident registry match"}</strong><small>{j.evidenceStatus} · {j.publisher||"publisher unresolved"} · ISSN {j.issn.join(", ")||"unresolved"} · {j.doajSignal?"DOAJ signal":"DOAJ not returned"} · APC {j.apcUsd===null?"unknown":`$${j.apcUsd}`}</small><ul>{j.cautions.slice(0,3).map(c=><li key={c}>{c}</li>)}</ul></article>)}</>}
        <div className={styles.sectionTitle}>Related high-signal scholarly landscape</div>{result.relatedWorks.slice(0,8).map(w=><div className={styles.work} key={w.id}><strong>{w.title}</strong><span>{w.year||"year unknown"} · {w.journal||"source unknown"} · {w.citedByCount} OpenAlex citations{w.doi?` · DOI ${w.doi}`:""}</span></div>)}
        <div className={styles.sectionTitle}>AI publisher strategy</div><pre className={styles.ai}>{result.aiReport||"No AI provider returned a report. Use the structured score, journal checks and related-work evidence above."}</pre>
        <div className={styles.sectionTitle}>Anti-scam rules for lecturers</div><ol>{result.assessment.scamShieldRules.map(x=><li key={x}>{x}</li>)}</ol>
      </>}</section>
    </div>
  </main>
}
