export type ScopusCostRoute =
  | "diamond-open-access"
  | "no-mandatory-fee"
  | "waiver-or-agreement"
  | "apc-likely";

export type ScopusJournal = {
  id: string;
  name: string;
  discipline: string;
  fieldTags: string[];
  publisher: string;
  costRoute: ScopusCostRoute;
  costNote: string;
  officialUrl: string;
  scopusSearchTerm: string;
  verificationNote: string;
};

export const scopusCostMeta: Record<ScopusCostRoute, { label: string; priority: number }> = {
  "diamond-open-access": { label: "Diamond OA / zero-APC route", priority: 0 },
  "no-mandatory-fee": { label: "No mandatory fee route", priority: 1 },
  "waiver-or-agreement": { label: "Waiver or agreement route", priority: 2 },
  "apc-likely": { label: "APC likely", priority: 3 },
};

const currentCoverageNotice =
  "Scopus coverage and fee policies can change. Confirm the exact title, ISSN, current coverage status and coverage years in Scopus Sources, then confirm fees on the journal's official author-guidelines page before submission.";

export const scopusJournals: ScopusJournal[] = [
  {
    id: "jmlr",
    name: "Journal of Machine Learning Research (JMLR)",
    discipline: "Computer Science & Artificial Intelligence",
    fieldTags: ["machine learning", "artificial intelligence", "statistics", "computer science", "data science"],
    publisher: "JMLR",
    costRoute: "diamond-open-access",
    costNote: "The journal states that papers are freely available and authors pay no publication fee. Recheck the current author information.",
    officialUrl: "https://jmlr.org/",
    scopusSearchTerm: "Journal of Machine Learning Research",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "joss",
    name: "Journal of Open Source Software (JOSS)",
    discipline: "Research Software & Computing",
    fieldTags: ["software", "open source", "research software", "computer science", "data science"],
    publisher: "Open Journals",
    costRoute: "diamond-open-access",
    costNote: "JOSS describes its model as free to read and free to publish. It requires a substantial open-source research software contribution.",
    officialUrl: "https://joss.theoj.org/",
    scopusSearchTerm: "Journal of Open Source Software",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "lmcs",
    name: "Logical Methods in Computer Science",
    discipline: "Computer Science & Logic",
    fieldTags: ["logic", "theoretical computer science", "formal methods", "programming languages", "computer science"],
    publisher: "LMCS",
    costRoute: "diamond-open-access",
    costNote: "A specialist open-access route. Confirm current charges and the article's fit with the journal's formal scope.",
    officialUrl: "https://lmcs.episciences.org/",
    scopusSearchTerm: "Logical Methods in Computer Science",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "theory-of-computing",
    name: "Theory of Computing",
    discipline: "Theoretical Computer Science",
    fieldTags: ["algorithms", "complexity", "cryptography", "theoretical computer science", "computation"],
    publisher: "Theory of Computing",
    costRoute: "diamond-open-access",
    costNote: "A highly selective specialist venue. Confirm fee policy, scope and submission requirements on the official site.",
    officialUrl: "https://theoryofcomputing.org/",
    scopusSearchTerm: "Theory of Computing",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "jstatsoft",
    name: "Journal of Statistical Software",
    discipline: "Statistics & Research Software",
    fieldTags: ["statistics", "statistical software", "data analysis", "r", "python", "research software"],
    publisher: "Foundation for Open Access Statistics",
    costRoute: "diamond-open-access",
    costNote: "Best suited to substantial statistical software and reproducible methodological contributions. Confirm the current fee statement.",
    officialUrl: "https://www.jstatsoft.org/",
    scopusSearchTerm: "Journal of Statistical Software",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "journal-political-ecology",
    name: "Journal of Political Ecology",
    discipline: "Environmental Social Science",
    fieldTags: ["political ecology", "environment", "development", "anthropology", "geography", "sustainability"],
    publisher: "University of Arizona Libraries",
    costRoute: "diamond-open-access",
    costNote: "A specialist route for political-ecology scholarship. Verify current charges, section fit and geographic/theoretical contribution.",
    officialUrl: "https://journals.librarypublishing.arizona.edu/jpe/",
    scopusSearchTerm: "Journal of Political Ecology",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "public-administration-development",
    name: "Public Administration and Development",
    discipline: "Public Administration & Development",
    fieldTags: ["public administration", "governance", "development", "public service", "government", "policy"],
    publisher: "Wiley",
    costRoute: "no-mandatory-fee",
    costNote: "A standard non-open-access publication route may avoid an APC; open-access charges are separate. Confirm the current options and African/development fit.",
    officialUrl: "https://onlinelibrary.wiley.com/journal/1099162x",
    scopusSearchTerm: "Public Administration and Development",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "local-government-studies",
    name: "Local Government Studies",
    discipline: "Local Government & Public Policy",
    fieldTags: ["local government", "decentralization", "governance", "public administration", "municipal", "public policy"],
    publisher: "Taylor & Francis",
    costRoute: "no-mandatory-fee",
    costNote: "The standard subscription route may have no mandatory APC. Open access is a separate paid option unless an agreement or waiver applies.",
    officialUrl: "https://www.tandfonline.com/journals/flgs20",
    scopusSearchTerm: "Local Government Studies",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "international-review-administrative-sciences",
    name: "International Review of Administrative Sciences",
    discipline: "Public Administration & Governance",
    fieldTags: ["public administration", "administrative science", "governance", "civil service", "public policy", "government"],
    publisher: "SAGE / International Institute of Administrative Sciences",
    costRoute: "no-mandatory-fee",
    costNote: "Investigate the standard publication route first; optional open access may carry a charge. Confirm current fees and geographic/theoretical contribution.",
    officialUrl: "https://journals.sagepub.com/home/ras",
    scopusSearchTerm: "International Review of Administrative Sciences",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "international-journal-public-administration",
    name: "International Journal of Public Administration",
    discipline: "Public Administration & Policy",
    fieldTags: ["public administration", "public policy", "governance", "public management", "civil service", "government"],
    publisher: "Taylor & Francis",
    costRoute: "no-mandatory-fee",
    costNote: "A standard subscription publication route may avoid an APC. Verify current submission options, scope and any optional open-access charge.",
    officialUrl: "https://www.tandfonline.com/journals/lpad20",
    scopusSearchTerm: "International Journal of Public Administration",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "revista-administracao-publica",
    name: "Revista de Administração Pública",
    discipline: "Public Administration & Management",
    fieldTags: ["public administration", "governance", "public management", "public policy", "government", "development"],
    publisher: "Fundação Getulio Vargas",
    costRoute: "diamond-open-access",
    costNote: "A potentially strong diamond/open route for public-administration research. Confirm current fees, language policy, scope and Scopus coverage.",
    officialUrl: "https://www.scielo.br/j/rap/",
    scopusSearchTerm: "Revista de Administracao Publica",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "survey-research-methods",
    name: "Survey Research Methods",
    discipline: "Social Science Research Methods",
    fieldTags: ["survey methodology", "questionnaire", "sampling", "measurement", "social science", "research methods"],
    publisher: "European Survey Research Association",
    costRoute: "diamond-open-access",
    costNote: "Appropriate only when the manuscript makes a methodological contribution to survey research, not merely because a survey was used.",
    officialUrl: "https://ojs.ub.uni-konstanz.de/srm/",
    scopusSearchTerm: "Survey Research Methods",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "ajet",
    name: "Australasian Journal of Educational Technology",
    discipline: "Education & Learning Technology",
    fieldTags: ["education", "educational technology", "online learning", "teaching", "higher education"],
    publisher: "Australasian Society for Computers in Learning in Tertiary Education",
    costRoute: "diamond-open-access",
    costNote: "A focused educational-technology venue. Confirm current fee policy and recent topic fit before preparing the manuscript.",
    officialUrl: "https://ajet.org.au/",
    scopusSearchTerm: "Australasian Journal of Educational Technology",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "ets",
    name: "Educational Technology & Society",
    discipline: "Education & Digital Learning",
    fieldTags: ["education", "technology", "digital learning", "instructional design", "learning analytics"],
    publisher: "International Forum of Educational Technology & Society",
    costRoute: "diamond-open-access",
    costNote: "Confirm the current publication-cost policy and ensure the study makes a clear technology-and-learning contribution.",
    officialUrl: "https://www.j-ets.net/",
    scopusSearchTerm: "Educational Technology and Society",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "canadian-higher-education",
    name: "Canadian Journal of Higher Education",
    discipline: "Higher Education",
    fieldTags: ["higher education", "university", "student", "policy", "teaching", "education"],
    publisher: "Canadian Society for the Study of Higher Education",
    costRoute: "diamond-open-access",
    costNote: "Confirm that the study speaks to the journal's audience and recheck current author charges and Scopus coverage.",
    officialUrl: "https://journals.sfu.ca/cjhe/index.php/cjhe",
    scopusSearchTerm: "Canadian Journal of Higher Education",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "philosophers-imprint",
    name: "Philosophers' Imprint",
    discipline: "Philosophy",
    fieldTags: ["philosophy", "ethics", "epistemology", "metaphysics", "logic", "political philosophy"],
    publisher: "University of Michigan Library",
    costRoute: "diamond-open-access",
    costNote: "A selective philosophy venue. Verify current submission status, scope and cost policy before targeting it.",
    officialUrl: "https://journals.publishing.umich.edu/phimp/",
    scopusSearchTerm: "Philosophers Imprint",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "glossa",
    name: "Glossa: A Journal of General Linguistics",
    discipline: "Linguistics",
    fieldTags: ["linguistics", "language", "syntax", "phonology", "semantics", "sociolinguistics"],
    publisher: "Open Library of Humanities",
    costRoute: "waiver-or-agreement",
    costNote: "Check the current publication-fee, institutional funding and waiver policy. Do not assume a waiver is automatic.",
    officialUrl: "https://www.glossa-journal.org/",
    scopusSearchTerm: "Glossa A Journal of General Linguistics",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "college-research-libraries",
    name: "College & Research Libraries",
    discipline: "Library & Information Science",
    fieldTags: ["library", "information science", "academic libraries", "information literacy", "higher education"],
    publisher: "Association of College and Research Libraries",
    costRoute: "diamond-open-access",
    costNote: "Verify current fees, article types and whether the evidence is sufficiently relevant to academic-library practice.",
    officialUrl: "https://crl.acrl.org/",
    scopusSearchTerm: "College and Research Libraries",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "emerging-infectious-diseases",
    name: "Emerging Infectious Diseases",
    discipline: "Public Health & Infectious Diseases",
    fieldTags: ["public health", "infectious disease", "epidemiology", "microbiology", "outbreak", "health"],
    publisher: "U.S. Centers for Disease Control and Prevention",
    costRoute: "no-mandatory-fee",
    costNote: "Confirm current charges and article category. Strong surveillance, epidemiology or public-health significance is essential.",
    officialUrl: "https://wwwnc.cdc.gov/eid/",
    scopusSearchTerm: "Emerging Infectious Diseases",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "balkan-medical-journal",
    name: "Balkan Medical Journal",
    discipline: "Medicine & Health Sciences",
    fieldTags: ["medicine", "clinical", "health", "biomedical", "public health", "surgery"],
    publisher: "Galenos Publishing House",
    costRoute: "diamond-open-access",
    costNote: "Confirm current author charges, study-design requirements and research-ethics documentation on the official site.",
    officialUrl: "https://balkanmedicaljournal.org/",
    scopusSearchTerm: "Balkan Medical Journal",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "acs-central-science",
    name: "ACS Central Science",
    discipline: "Chemistry & Interdisciplinary Science",
    fieldTags: ["chemistry", "materials", "chemical biology", "nanotechnology", "interdisciplinary science"],
    publisher: "American Chemical Society",
    costRoute: "diamond-open-access",
    costNote: "ACS currently describes this title as diamond open access. Recheck the policy and expect a very high novelty threshold.",
    officialUrl: "https://pubs.acs.org/journal/acscii",
    scopusSearchTerm: "ACS Central Science",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "beilstein-organic-chemistry",
    name: "Beilstein Journal of Organic Chemistry",
    discipline: "Organic Chemistry",
    fieldTags: ["organic chemistry", "synthesis", "catalysis", "medicinal chemistry", "chemical biology"],
    publisher: "Beilstein-Institut",
    costRoute: "diamond-open-access",
    costNote: "Confirm the current no-fee statement and ensure the work has a strong organic-chemistry contribution.",
    officialUrl: "https://www.beilstein-journals.org/bjoc/",
    scopusSearchTerm: "Beilstein Journal of Organic Chemistry",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "brazilian-journal-geology",
    name: "Brazilian Journal of Geology",
    discipline: "Earth & Geological Sciences",
    fieldTags: ["geology", "earth science", "geochemistry", "geophysics", "mining", "environment"],
    publisher: "Brazilian Geological Society",
    costRoute: "diamond-open-access",
    costNote: "Verify current fees and whether the geographic and scientific contribution fits the journal's present scope.",
    officialUrl: "https://www.scielo.br/j/bjgeo/",
    scopusSearchTerm: "Brazilian Journal of Geology",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "perspectives-ecology-conservation",
    name: "Perspectives in Ecology and Conservation",
    discipline: "Ecology & Conservation",
    fieldTags: ["ecology", "conservation", "biodiversity", "environment", "sustainability", "forest"],
    publisher: "Brazilian Association for Ecological Science and Conservation",
    costRoute: "no-mandatory-fee",
    costNote: "Check the current sponsored-publication policy and confirm a clear conservation-science or policy contribution.",
    officialUrl: "https://www.sciencedirect.com/journal/perspectives-in-ecology-and-conservation",
    scopusSearchTerm: "Perspectives in Ecology and Conservation",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "borsa-istanbul-review",
    name: "Borsa Istanbul Review",
    discipline: "Economics, Finance & Business",
    fieldTags: ["finance", "economics", "business", "capital market", "banking", "investment"],
    publisher: "Borsa Istanbul",
    costRoute: "no-mandatory-fee",
    costNote: "Confirm the current sponsored-publication policy, scope and data/method expectations before submission.",
    officialUrl: "https://www.sciencedirect.com/journal/borsa-istanbul-review",
    scopusSearchTerm: "Borsa Istanbul Review",
    verificationNote: currentCoverageNotice,
  },
  {
    id: "nuclear-engineering-technology",
    name: "Nuclear Engineering and Technology",
    discipline: "Engineering & Energy",
    fieldTags: ["nuclear", "engineering", "energy", "materials", "reactor", "radiation"],
    publisher: "Korean Nuclear Society",
    costRoute: "no-mandatory-fee",
    costNote: "Confirm the current sponsored-publication route, scope, safety requirements and charges on the official journal page.",
    officialUrl: "https://www.sciencedirect.com/journal/nuclear-engineering-and-technology",
    scopusSearchTerm: "Nuclear Engineering and Technology",
    verificationNote: currentCoverageNotice,
  },
];

export const scopusDisciplines = [...new Set(scopusJournals.map((journal) => journal.discipline))];

export function scopusSourcesUrl(searchTerm = "") {
  const base = "https://www.scopus.com/sources.uri";
  return searchTerm ? `${base}?searchterm1=${encodeURIComponent(searchTerm)}&field1=TITLE` : base;
}
